---
title: "Data Science Applied to Ag - Final Project - Design"
author: Md Ariful Islam Sohag & Polycarpe Mizero
format:
  html:
    code-fold: false
    embed-resources: true
    toc: true
    number-sections: true
    theme: cerulean
editor: 
  markdown: 
    wrap: 72
---

# Instructions

This file contains both the **instructions** for the mid-term project
and placeholders for your code. You are required to use this file to
produce code, output, and answers to the questions below.

Besides simply creating output, make sure to interpret the output. You
will need to create tables and/or plots to arrive at the answers, and
then comment on what you found below it.

To get you setup, you will need to:

-   Student #1: create a repository on your GitHub account. You can call
    this repository "2025dsa_finalproject_groupX", **where X is the
    number of your group**. Make it public, add a README, add a
    .gitignore for R.\
-   Student #1: follow the steps we did in class to start a new RStudio
    project with version control.\
-   Student #1: in your computer, create the sub-folders code, data,
    output, and move your data set into the `data` folder. Also, student
    1 moves this current script into the `code` folder. Do a git stage,
    commit, push.\
-   Student #1: on GitHub, go the repository settings and invite your
    partner to be a collaborator in the repository. That will give them
    push permission.\
-   Now, both students should clone this repository on their computers
    like we did in class. Make sure this step works well and that you
    can pull and push from GitHub.\
-   Student 2, after cloning, does a git pull to get all these updates
    on their computer.\
-   Student 1 and 2 work together to update the README file. README
    files should explain what the repository is about, the goals of that
    project, who is working in it, and any other important details you
    may find.

# Introduction

Describe here the introduction of your problem. Consider this as a
shortened version of your paper, where you will briefly discuss in 3-4
paragraphs what is the issue/gap in literature, and how the data you
collected will help answer this gap.

Reliance on renewable energy sources to minimize dependency on fossil
fuels is considered one of the strategies to mitigate the global climate
change crisis. Several government agencies and international
organizations have implemented policies to support renewable energy. In
the United States, the Department of Energy; the Department of
Transportation, and the Department of Agriculture established the
Sustainable Aviation Fuel (SAF) Grand Challenge. An important roadmap of
the SAF Grand Challenge is to produce 11.35 billion liters of SAF
annually by 2030 and 132.5 billion liters by 2050 (DOE, 2022). The road
map places an enormous demand for SAF production, but the demand must be
met in light of sustainability and food security.

Carinata (Brassica carinata), also known as Ethiopian mustard, is a
nonfood oilseed crop with a low carbon footprint, and it was listed as
an ICAO-approved SAF in 2019.Carinata offers more than just an oilseed
crop for SAF production. Its production will provide many ecosystem
benefits, such as decreasing weed infestation, increasing beneficial
nematodes, and retaining more water for the following crop. carinata can
be cultivated in the winter in several areas of the Southeastern United
States to create a source of off-season income for growers without
displacing food and fiber production.

Correct timing of fertilizer application is critical because crops
require different amounts of nutrients at every growth stage. Since
carinata is an emerging crop in the southeast United States, it is very
important to know the nutrient recommendation and appropriate fertility
recommendation of carinata for successful production in the existing
cropping system. To date, the nutrient sufficiency ranges for canola are
adopted for carinata production (George et al., 2023). One study was
conducted in North Carolina to derive nutrient sufficiency ranges for
carinata used in vitro conditions showed that boron deficiency had the
greatest impact on the overall production of carinata (Cockson et al.,
2021). However, another study conducted in Logan, UT on 36 different
plant species showed that the plant and soil values were overestimated
in greenhouse conditions than under field conditions(Forero et al.,
2019). Thus, the study conducted in North Carolina confirmed that
carinata had different tissue concentration levels at different stages,
but the nutrient levels could not be readily applied to field
conditions. Therefore, the main objective of this study is to determine
the nutrient-sufficiency range of carinata in the Southeast United
States under different field conditions. Only a clear understanding of
the deficiency and toxicity of different macro and micronutrients will
help us to establish an ideal fertilizer recommendation for carinata in
the southeast United States.

# Hypothesis and objectives

Describe here your hypothesis, followed by your objectives. Make sure
your hypothesis are testable and bold, and objectives are clear.

**Hypothesis**: Higher nutrient content will increase carinata yield.

**Objective**: to determine the nutrient-sufficiency range of carinata
in the Southeast United States under different field conditions

# Material and Methods

Describe here your overall material and methods as it pertains to the
analysis you will conduct, including study description, site/setup
description, what equipment was used, etc. just like you would in a
paper. Make sure to clearly explain what was measured and how.

The study was conducted at the University of Georgia Coastal Plains
station in Tifton, GA, and the North Florida Research and Education
Center in Live Oak, FL.

The five treatments were consist of: (a) Treatment 1 (T1): No fertilizer
application, which will serve as the control treatment. (b) Treatment 2
(T2): Fertilizer application following standard recommendation for
commercial production of carinata. The fertilizer application will be
limited to supplying N, P, K, and S. The rate will depend on soil test
analyses, but N application will be limited to 80 lbs/ac. Thus, the two
sites may have different rates of P, K, and S depending on the soil test
results. (c) Treatment 3 (T3): Fertilizer blend to supply 40 lbs/ac N,
30 lbs/ac P2O5, 30 lbs/ac K2O, 15 lbs/ac Ca, 10 lbs/ac Mg, 10 lbs/ac S,
3 lbs/ac Fe, 3 lbs/ac Mn, 2 lbs/ac Zn, 1 lbs/ac B, and 1 lbs/ac Cu. (d)
Treatment 4 (T4): Fertilizer blend to supply 3× the rates specified in
T3. (e) Treatment 5 (T5): Fertilizer blend to supply 6× the rates
specified in T3.

Nujeet 400 carinata hybrid will be planted at a seeding rate of (3-3.5
lbs speed/ac) appropriate to achieve a good stand.

For the blended fertilizer treatments, 50% of the recommended fertilizer
rate for T3, will be applied at the initial stage of the planting.
Fertilizer will be incorporated well into the soil. The remaining
fertilizer rates, according to the treatment, will be applied in the
early spring, shortly after the crops resume growth from the cold
season.

-   T1=

-   T2=

-   T3=

-   T4=

-   T5=

canola settings was applied when combine machine used for harvesting of
carinata.

## Study design

Clearly describe your study design here, including treatment design
(which factors and levels, the hierarchy among them, etc.), and your
experimental design (number of reps/blocks, how was randomization
performed, etc.), as we talked about in class.

The study was set as a RCBD, with the 4 replication.

Number of replicates: 4\
Number of treatments: 5 fertilizer rate\
Number of observations: 5 x 4 = 20

## Statistical analysis

Describe here your statistical analysis, including what type of ANOVA
model you ran (based on the design above), what was your response
variable, what were your explanatory variables and how were the
explanatory variables treated (random or fixed). Provide your alpha
level. Explain which function from which package you used to analyze
this data. Explain how you checked linear model assumptions and whether
or not they were met. Overall, make sure you explain in sufficient
detail that, if given your data, a knowledgeable person would be able to
reproduce your analysis exactly.

ANOVA model Response variable Explanatory variable How the explanatory
was treated (random or fixed) alpha level function: package: linear
model assumptions

Response variable: Carinata seed yield

Explanatory variable: Fertilizer rates

Fixed factors: fertilizer rate

Random factor: blocks

Data was analyzed with a linear mixed model using lme4 package, and the
significance level was assessed at p = 0.05

```{r}

```

# Results

Here is where the coding is going to happen, and it will be completely
up to you. Include under this section as many sub-sections (using ##)
and as many chunks needed to create the analytical workflow for your
analysis, starting at loading packages and data, wrangling, EDA,
modeling, assumptions checking, ANOVA table, means, pairwise
comparisons, and final publication-quality plot.

Make sure to run a model that reflects your study design. Even if your
study design does not include one of the designs covered in class, you
are still expected to run the most appropriate model. If you need help
for references, let me know.

Before each chunk, describe the steps being performed in that chunk. For
example, "Here I will load the data".

If a chunk produces output, like printing a data frame, statistical
summary, a plot, ANOVA table, etc., make sure to write text interpreting
what you see and how you can/will use that information to move forward
to the next steps in the workflow.

# Team work in GitHub

Whether you are working with your future-self or as duos, make sure to
stage, commit, and push after finishing each of the sub-sections above.
When committing, write commit messages that are short and descriptive
(e.g., finished wrangling).

If you are working in duos, make sure to split the workload. I will
check your collaborative work through the commit history, and if one
student has contributed significantly more than the other, than that
will impact grades.

**Tip 1**: to avoid merge conflicts, make sure to **pull** first, and
then start working locally. That will ensure that any changes made by
your partner will be "downloaded" before you make changes to the files
locally.

**Tip 2**: make use of the Issues on this repository to set up to-do
lists and assign tasks to different people. You can also use each
issue/task to discuss how things should be run and get to an agreement.

# Submitting your work

Once you have developed all the code and answers, make sure to Render
this quarto file.

**Notes on rendering**:

-   Make sure to render your work and inspect how the final html look
    like.\
-   If it does not look professional for whatever reason, then fix the
    issue, re-render it, recheck.\
-   Only send me your work once your html file looks professional.\
-   Some potential issues you may encounter and how to fix them:
    -   Some times your code may be creating a table output that is
        waaay to long and cumbersome to scroll through when rendered. If
        this is the case, make it more professional looking by using the
        `head()` function to only print the first handful of rows
        (instead of thousands of rows).

    -   **DO NOT** delete the file's heading levels (# and ##). They set
        up the proper heading 1 and 2 levels, and I use them to guide my
        grading.

    -   If a given chunk is also outputting warnings or messages,
        inhibit this behavior by changing the chunk options `message`
        and `warning` to `FALSE`.

    -   If, after rendered, 2 lines of text are connected and you wish
        to "break line" between them, add 2 extra spaces after the first
        one.

After rendering, an .html file will be created on your `code` folder.

Rename this file to `LASTNAME1-LASTNAME2_finalproject.html`.\
For ex., `Bastos-Mendes_finalproject.html`.

Submit the html file on eLC by **April 30th** 11:59 pm.
